=== dotike/open-arcade/misc/galaga/schema/galaga-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "http://example.com/example.json",
    "type": "object",
    "title": "Galaga schema",
    "description": "The schema that defines a Galaga layer",
    "default": {},
    "required": [
        "user",
        "createTime",
        "name",
        "version",
        "components"
    ],
    "properties": {
        "user": {
            "$id": "#/properties/user",
            "type": "string",
            "title": "User",
            "description": "The user who created the schema"
        },
        "createTime": {
            "$id": "#/properties/createTime",
            "type": "string",
            "title": "CreateTime",
            "description": "The time (%Y/%m/%d/%H/%M) the asteroid json is created"
        },
        "name": {
            "$id": "#/properties/name",
            "type": "string",
            "title": "Name",
            "description": "The Arcade name for the Galaga layer"
        },
        "version": {
            "$id": "#/properties/version",
            "type": "integer",
            "title": "Version",
            "description": "The version of the galaga"
        },
        "components": {
            "$id": "#/properties/components",
            "type": "object",
            "title": "Components",
            "description": "An explanation about the purpose of this instance."
        }
    }
}

=== dotike/open-arcade/misc/galaga/galaga-examples/kind_raw.json
{
    "user": "first.last",
    "createTime": "2021/07/09/19/54",
    "name": "kind_raw",
    "version": 1,
    "components": {
        "eks": {
            "location": "galaga/galaga/gsd/eks/latest/latest.json",
            "overrides": {
                "service_options/eks_version": "1.20"
            }
        },
        "nodegroup": {
            "location": "galaga/galaga/gsd/nodegroup/latest/latest.json",
            "overrides": {}
        },
        "alb": {
            "location": "galaga/galaga/gsd/alb/latest/latest.json",
            "overrides": {}
        }
    }
}

=== dotike/open-arcade/misc/galaga/galaga-examples/arcadebase.json
{
    "user": "andy.dunlap",
    "createTime": "2022/04/26/20/02",
    "name": "arcadebase",
    "version": 2,
    "components": {
        "asteroids-eks": {
            "location": "gsd/asteroids-eks/default.json",
            "overrides": {}
        },
        "asteroids-msk": {
            "location": "gsd/asteroids-msk/default.json",
            "overrides": {}
        },
        "secretsmanager": {
            "location": "gsd/secretsmanager/default.json",
            "overrides": {}
        }
    }
}
